### ISSUE TITLE
typo conflit

### ISSUE THREAD

**Issue by worcq** [YGomiero/typographe#1]
je viens de télécharger le plugin
je l'active
j'ouvre le site en frontend 
erreur affiche pagebuilder et le n° de la page appelée
je désactive le plugin et l'appel à la page fonctionne normalement
j'imagine que le plugin typo apporte un correctif qui n'a pas lieu d'être, parce déjà pris en compte?
Merci de m'aider à voir clair
Willy

**Comment by YGomiero** [comment]
effectivement, l'utilisation de page builder dans les articles peut perturber le contenu. C'est un choix tout comme l'usage de shortcode. Merci pour l'info, je vais créer un message d'avertissement car cette configuration n'est pas prévue pour le moment.
