### ISSUE TITLE
Compatibilité J4

### ISSUE THREAD

**Issue by fontanil** [YGomiero/typographe#3]
Bonjour,

A priori, il suffit de modifier la ligne 27 de typographe.php en $app->isClient('administrator') (au lieu de isAdmin()) pour que e plugin soit compatible J4. :)

**Comment by fontanil** [comment]
Un bug que je n'avais encore jamais remarqué : en J3 comme en J4 (dernières versions 3.10.4 et 4.0.5), lorsqu'une image est insérée dans un article (avec JCE ou avec TinyMCE), dès que le plugin est activé,  bien que l'adresse soit correcte dans le code-source, l'image ne s'affiche pas sur le site. 
Inséré avec Tiny, son code est <img src="/images/ptde­la­serre_vign.jpg" alt="" /> mais seul le contenu de "alt" s'insère dans le texte si je l'ajoute.
Insérée avec JCE, l'espace de l'image matérialisé, et si j'essaie d'ouvrir l'image dans un autre onglet, son nom s'affiche /images/ptde%C2%ADla%C2%ADserre.jpg dans la barre d'adresse.

**Comment by YGomiero** [comment]
Corrigé ! Merci.

**Comment by fontanil** [comment]
Merci Yann !
Il faut que je retrouve le site sur lequel j'avais testé... ;)
